### ISSUE TITLE
pls update to Font Awesome 6 pro

### ISSUE THREAD

**Issue by nomadicshiv** [tallesairan/FA5PRO#1]
pls update to Font Awesome 6 pro

**Comment by tallesairan** [comment]
[FA6 PRO](https://github.com/tallesairan/FA5PRO/tree/fa6) 
:)

**Comment by Cubik65536** [comment]
Can you update to the new version of FA6, please? /cc @tallesairan

**Comment by tallesairan** [comment]
Merged

**Comment by Cubik65536** [comment]
> Merged

But according to [Font Awesome.com's Changelog](https://fontawesome.com/v6/docs/changelog/), there are a lot of updates recently, so #2 that has been merged is slightly outdated I assume?

**Comment by tallesairan** [comment]
I can't update again, font awesome blocked my profile and my purchase

**Comment by Cubik65536** [comment]
> I can't update again, font awesome blocked my profile and my purchase

Oh, okay, that’s sad…
