### ISSUE TITLE
Can I use it with React?

### ISSUE THREAD

**Issue by Aniket-IN** [tallesairan/FA5PRO#3]
Hi, I needed a lil help.. 

Can I use it with React, I mean i know I can just simply import all icons. 

But is there any way to import only those icons which I wanna use. 

like: 

`
import { iconA, iconB } from 'fontAwesome';
`

Thanks in advance :)

**Comment by omar-abdelatif** [comment]
i think you can just go to node modules file then font awesome folder and replace the css folder and js and webfonts, i'm now using fontawesome 5.15.4 pro with this method, but first i installed by npm first

**Comment by tallesairan** [comment]
sorry I don't understand anything about react
