### ISSUE TITLE
How do we actually use this without a pro subscription?

### ISSUE THREAD

**Issue by alexjshaw** [tallesairan/FA5PRO#8]
I'm probably being a bit dim here, but I'm currently having a hard time actually figuring out how to use this.

I've got the free font awesome files set up and installed, working fine, but can't figure out how to set these pro icons up!

What's the process for making them useable?

Thanks!

**Comment by tallesairan** [comment]
The easiest and simplest way to use it:

Download the repository.
You can create a folder called "assets" and place the "webfonts" and "css" folders inside it.
You can include the CSS file in your web page: <link rel="stylesheet" href="/assets/css/all.min.css">
After that, you can use the fonts smoothly.
Another more advanced way is to use SCSS, but I'm not a frontend expert, so I can't help with that.
